/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EmployeeListImport } from './routes/employee-list'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const EmployeeListRoute = EmployeeListImport.update({
  id: '/employee-list',
  path: '/employee-list',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/employee-list': {
      id: '/employee-list'
      path: '/employee-list'
      fullPath: '/employee-list'
      preLoaderRoute: typeof EmployeeListImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employee-list': typeof EmployeeListRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employee-list': typeof EmployeeListRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/employee-list': typeof EmployeeListRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/employee-list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/employee-list'
  id: '__root__' | '/' | '/employee-list'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeeListRoute: typeof EmployeeListRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeeListRoute: EmployeeListRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/employee-list"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/employee-list": {
      "filePath": "employee-list.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
